name: Daily data refresh

on:
  schedule:
    # 10:00 America/New_York crosses DST; run at both UTC times and let script be idempotent
    - cron: '0 14 * * *' # 10:00 EDT
    - cron: '0 15 * * *' # 10:00 EST
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: data-refresh
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute branch date (America/New_York)
        id: date
        run: |
          echo "today=$(TZ=America/New_York date +%F)" >> $GITHUB_OUTPUT

      - name: Resolve PR token
        run: |
          if [ -n "${{ secrets.CREATE_PR_TOKEN }}" ]; then
            echo "PR_TOKEN=${{ secrets.CREATE_PR_TOKEN }}" >> $GITHUB_ENV
          else
            echo "PR_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          fi

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Recreate PR branch fresh (no reuse)
        run: |
          set -e
          BR=auto-${{ steps.date.outputs.today }}
          git fetch origin || true
          # Delete local branch if it exists
          if git show-ref --verify --quiet refs/heads/$BR; then
            git branch -D $BR
          fi
          # Delete remote branch if it exists
          if git ls-remote --exit-code --heads origin $BR >/dev/null 2>&1; then
            git push origin --delete $BR
          fi
          # Create fresh branch and push
          git checkout -b $BR
          git commit --allow-empty -m "chore: prepare data refresh for ${{ steps.date.outputs.today }}"
          git push --set-upstream origin $BR

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: scripts/requirements.txt

      - name: Setup Chrome (for Selenium)
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome version
        run: |
          google-chrome --version || chromium --version || true

      - name: Create venv and install requirements
        working-directory: scripts
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full extraction
        working-directory: scripts
        env:
          TZ: America/New_York
        run: |
          . venv/bin/activate
          python full_extraction.py --headless

      - name: Commit content changes to PR branch
        run: |
          BR=auto-${{ steps.date.outputs.today }}
          git checkout $BR
          git pull --ff-only || true
          git add content/** || true
          if ! git diff --cached --quiet; then
            git commit -m "data: auto-refresh content for ${{ steps.date.outputs.today }}"
            git push
          else
            echo "No content changes to commit."
          fi

      - name: Create PR and enable auto-merge
        env:
          GH_TOKEN: ${{ env.PR_TOKEN }}
        run: |
          set -e
          BR=auto-${{ steps.date.outputs.today }}
          gh pr create \
            --title "Data refresh for ${{ steps.date.outputs.today }}" \
            --body "Automated data refresh run for ${{ steps.date.outputs.today }}" \
            --base main \
            --head "$BR"
          pr_number=$(gh pr view "$BR" --json number -q .number)
          gh pr merge "$pr_number" --squash --auto


